### ISSUE TITLE
LZ4 files unable to be opened due to missing header 

### ISSUE THREAD

**Issue by jeremyabel** [gtreshchev/RuntimeArchiver#5]
Hello,

It looks like UE's LZ4 setup is just the basic compression, it doesn't contain the required lz4frame library required to generate a file that can actually be opened by lz4 command line tools. As such, I am not able to open the LZ4 files generated by your plugin. Is there any way you've managed to open them? If not, it's probably worth documenting this.

Thanks!

**Comment by gtreshchev** [comment]
Hello, the LZ4 archiver operates within the tar.lz4 (tlz4) context, that is, it uses the Tar implementation under the hood. So, to decompress the archive compressed in LZ4, you could use the following command: 
```
lz4 -d ArchiveName.tar.lz4 -c | tar xvf -
```

**Comment by gtreshchev** [comment]
You could also use this shell code as a reference: https://gist.github.com/bvaudour/48d972a045bc28767fab

**Comment by jeremyabel** [comment]
Ahhh ok, I tried a bunch of stuff but I'm on Windows so I wasn't sure what to do. I was using 7zip and it was getting confused by the file. Thanks!
